version: "3.7"

services:
    app:
        image: echostream2
        container_name: es2
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        ports:
            - 6824:6824
        restart: on-failure
    redis:
        image: redis
        container_name: rds
        ports:
            - 6379:6379
        restart: on-failure
